app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/recipebook
      username: dev_alec
      password: 'password'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/recipebook
    user: dev_alec
    password: password
    enabled: true